# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  
  push:
    branches:
      - main
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      
      - name: Delete tag
        run: '(git push --delete origin latest)'
        
      - name: Push new tag
        run: |
          'git tag -a latest'
          'git push origin latest'
      
      - name: Create Release
        uses: ncipollo/release-action@v1.8.8
        with:
          commit: 'main'
          tag: 'latest'
