# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  
  push:
    branches:
      - main
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Test export
        run: '"Hello there" | Out-File $Env:GITHUB_ENV'
      
      - name: Print export
        run: 'Write-Host "$($env:JPTEST)"'
